"""empty message

Revision ID: 462dcd428f2b
Revises: 
Create Date: 2024-02-14 21:48:41.316774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '462dcd428f2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tittle', sa.String(length=100), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('day', sa.String(length=100), nullable=False),
    sa.Column('time', sa.String(length=100), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('meetups_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meetups_id'], ['meetups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
