"""empty message

Revision ID: 9e753a847699
Revises: 
Create Date: 2024-02-07 23:24:26.990848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e753a847699'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meetups_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'meetups', ['meetups_id'], ['id'])
        batch_op.drop_column('Meetups')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Meetups', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('meetups_id')

    # ### end Alembic commands ###
